export const LEGAL_PERSON_TYPES = [
  // Más importantes primero
  "Sociedad Anónima (S.A.)",
  "Sociedad de Responsabilidad Limitada (S.R.L.)",
  "Sociedad Internacional de Negocios (SIB)",
  "Fundación de Interés Privado",
  "Sucursal en el extranjero",
  
  // Resto de la lista
  "Sociedad de Emprendimiento",
  "Sociedad Colectiva",
  "Sociedad en Comandita Simple",
  "Sociedad en Comandita por Acciones",
  "Sociedad Civil",
  "Empresa Individual de Responsabilidad Limitada (EIRL)",
  "Sucursal de Sociedad Extranjera",
  "Fideicomiso",
  "Asociación Civil",
  "Asociación de Interés Público (AIP)",
  "Organización No Gubernamental (ONG)",
  "Fundación de Interés Público",
  "Cooperativa",
  "Asociación Religiosa",
  "Corporación Pública",
  "Empresa Estatal",
  "Entidad Autónoma",
  "Entidad Semiautónoma",
  "Municipio",
  "Junta Comunal",
  "Universidad Pública",
  "Sindicato",
  "Federación",
  "Confederación",
  "Consorcio",
  "Joint Venture",
  "Sociedad Accidental",
  "Sociedad de Hecho",
  "Cámara de Comercio",
  "Patronato",
  "Comité",
  "Colegio Profesional",
  "Caja de Ahorros y Crédito Cooperativa",
  "Fundación Bancaria",
  "Zona Franca bajo Persona Jurídica",
  "Sociedad Holding",
  "Sociedad Offshore",
  "Sociedad de Inversión",
  "Sociedad Inmobiliaria",
  "Sociedad Financiera",
  "Sociedad Bancaria",
  "Sociedad Aseguradora",
  "Reaseguradora",
  "Casa de Valores",
  "Administradora de Fondos",
  "Fundación Familiar",
  "Sociedad Agropecuaria",
  "Sociedad Marítima",
  "Sociedad Naviera",
  "Sociedad Industrial",
  "Sociedad Comercial",
  "Sociedad de Servicios",
  "Sociedad Tecnológica",
  "Sociedad Profesional",
  "Sociedad Médica",
  "Sociedad de Abogados",
  "Sociedad Contable",
  "Sociedad Auditora",
  "Sociedad Constructora",
  "Sociedad Minera",
  "Sociedad Energética",
  "Sociedad Turística",
  "Sociedad Hotelera",
  "Sociedad de Transporte",
  "Sociedad Logística",
  "Sociedad Educativa",
  "Sociedad Editorial",
  "Sociedad de Telecomunicaciones",
  "Sociedad de Capital Variable",
  "Sociedad Mixta",
  "Asociación de Propietarios",
  "Condominio con personalidad jurídica",
  "Fundación Educativa",
  "Fundación Cultural",
  "Fundación Científica",
  "Asociación Ambiental",
  "Asociación Benéfica",
  "Asociación Empresarial",
  "Asociación Profesional",
  "Asociación Cultural",
  "Asociación Estudiantil",
  "Asociación Comunitaria"
]
