-- Migration: 20260520000004_seed_all_countries.sql
-- Goal: Seed a highly comprehensive database of all world countries, their ISO codes, phone prefixes, and flag emojis

DELETE FROM public.countries;

INSERT INTO public.countries (name, iso_code, phone_prefix, flag_emoji, is_default) VALUES
('Panamá', 'PA', '+507', '🇵🇦', true),
('Estados Unidos', 'US', '+1', '🇺🇸', false),
('España', 'ES', '+34', '🇪🇸', false),
('Colombia', 'CO', '+57', '🇨🇴', false),
('Costa Rica', 'CR', '+506', '🇨🇷', false),
('Venezuela', 'VE', '+58', '🇻🇪', false),
('México', 'MX', '+52', '🇲🇽', false),
('Afganistán', 'AF', '+93', '🇦🇫', false),
('Albania', 'AL', '+355', '🇦🇱', false),
('Alemania', 'DE', '+49', '🇩🇪', false),
('Andorra', 'AD', '+376', '🇦🇩', false),
('Angola', 'AO', '+244', '🇦🇴', false),
('Antigua y Barbuda', 'AG', '+1-268', '🇦🇬', false),
('Arabia Saudita', 'SA', '+966', '🇸🇦', false),
('Argelia', 'DZ', '+213', '🇩🇿', false),
('Argentina', 'AR', '+54', '🇦🇷', false),
('Armenia', 'AM', '+374', '🇦🇲', false),
('Australia', 'AU', '+61', '🇦🇺', false),
('Austria', 'AT', '+43', '🇦🇹', false),
('Azerbaiyán', 'AZ', '+994', '🇦🇿', false),
('Bahamas', 'BS', '+1-242', '🇧🇸', false),
('Bangladés', 'BD', '+880', '🇧🇩', false),
('Barbados', 'BB', '+1-246', '🇧🇧', false),
('Baréin', 'BH', '+973', '🇧🇭', false),
('Bélgica', 'BE', '+32', '🇧🇪', false),
('Belice', 'BZ', '+501', '🇧🇿', false),
('Benín', 'BJ', '+229', '🇧🇯', false),
('Bielorrusia', 'BY', '+375', '🇧🇾', false),
('Birmania / Myanmar', 'MM', '+95', '🇲🇲', false),
('Bolivia', 'BO', '+591', '🇧🇴', false),
('Bosnia y Herzegovina', 'BA', '+387', '🇧🇦', false),
('Botsuana', 'BW', '+267', '🇧🇼', false),
('Brasil', 'BR', '+55', '🇧🇷', false),
('Brunéi', 'BN', '+673', '🇧🇳', false),
('Bulgaria', 'BG', '+359', '🇧🇬', false),
('Burkina Faso', 'BF', '+226', '🇧🇫', false),
('Burundi', 'BI', '+257', '🇧🇮', false),
('Bután', 'BT', '+975', '🇧🇹', false),
('Cabo Verde', 'CV', '+238', '🇨🇻', false),
('Camboya', 'KH', '+855', '🇰🇭', false),
('Camerún', 'CM', '+237', '🇨🇲', false),
('Canadá', 'CA', '+1', '🇨🇦', false),
('Catar', 'QA', '+974', '🇶🇦', false),
('República Centroafricana', 'CF', '+236', '🇨🇫', false),
('Chad', 'TD', '+235', '🇹🇩', false),
('República Checa', 'CZ', '+420', '🇨🇿', false),
('Chile', 'CL', '+56', '🇨🇱', false),
('China', 'CN', '+86', '🇨🇳', false),
('Chipre', 'CY', '+357', '🇨🇾', false),
('Congo', 'CG', '+242', '🇨🇬', false),
('R.D. Congo', 'CD', '+243', '🇨🇩', false),
('Corea del Norte', 'KP', '+850', '🇰🇵', false),
('Corea del Sur', 'KR', '+82', '🇰🇷', false),
('Costa de Marfil', 'CI', '+225', '🇨🇮', false),
('Croacia', 'HR', '+385', '🇭🇷', false),
('Cuba', 'CU', '+53', '🇨🇺', false),
('Dinamarca', 'DK', '+45', '🇩🇰', false),
('Dominica', 'DM', '+1-767', '🇩🇲', false),
('República Dominicana', 'DO', '+1-809', '🇩🇴', false),
('Ecuador', 'EC', '+593', '🇪🇨', false),
('Egipto', 'EG', '+20', '🇪🇬', false),
('El Salvador', 'SV', '+503', '🇸🇻', false),
('Emiratos Árabes Unidos', 'AE', '+971', '🇦🇪', false),
('Eritrea', 'ER', '+291', '🇪🇷', false),
('Eslovaquia', 'SK', '+421', '🇸🇰', false),
('Eslovenia', 'SI', '+386', '🇸🇮', false),
('Estonia', 'EE', '+372', '🇪🇪', false),
('Etiopía', 'ET', '+251', '🇪🇹', false),
('Filipinas', 'PH', '+63', '🇵🇭', false),
('Finlandia', 'FI', '+358', '🇫🇮', false),
('Fiyi', 'FJ', '+679', '🇫🇯', false),
('Francia', 'FR', '+33', '🇫🇷', false),
('Gabón', 'GA', '+241', '🇬🇦', false),
('Gambia', 'GM', '+220', '🇬🇲', false),
('Georgia', 'GE', '+995', '🇬🇪', false),
('Ghana', 'GH', '+233', '🇬🇭', false),
('Granada', 'GD', '+1-473', '🇬🇩', false),
('Grecia', 'GR', '+30', '🇬🇷', false),
('Guatemala', 'GT', '+502', '🇬🇹', false),
('Guinea', 'GN', '+224', '🇬🇳', false),
('Guinea-Bisáu', 'GW', '+245', '🇬🇼', false),
('Guinea Ecuatorial', 'GQ', '+240', '🇬🇶', false),
('Guyana', 'GY', '+592', '🇬🇾', false),
('Haití', 'HT', '+509', '🇭🇹', false),
('Honduras', 'HN', '+504', '🇭🇳', false),
('Hungría', 'HU', '+36', '🇭🇺', false),
('India', 'IN', '+91', '🇮🇳', false),
('Indonesia', 'ID', '+62', '🇮🇩', false),
('Irak', 'IQ', '+964', '🇮🇶', false),
('Irán', 'IR', '+98', '🇮🇷', false),
('Irlanda', 'IE', '+353', '🇮🇪', false),
('Islandia', 'IS', '+354', '🇮🇸', false),
('Israel', 'IL', '+972', '🇮🇱', false),
('Italia', 'IT', '+39', '🇮🇹', false),
('Jamaica', 'JM', '+1-876', '🇯🇲', false),
('Japón', 'JP', '+81', '🇯🇵', false),
('Jordania', 'JO', '+962', '🇯🇴', false),
('Kazajistán', 'KZ', '+7', '🇰🇿', false),
('Kenia', 'KE', '+254', '🇰🇪', false),
('Kirguistán', 'KG', '+996', '🇰🇬', false),
('Kiribati', 'KI', '+686', '🇰🇮', false),
('Kuwait', 'KW', '+965', '🇰🇼', false),
('Laos', 'LA', '+856', '🇱🇦', false),
('Lesoto', 'LS', '+266', '🇱🇸', false),
('Letonia', 'LV', '+371', '🇱🇻', false),
('Líbano', 'LB', '+961', '🇱🇧', false),
('Liberia', 'LR', '+231', '🇱🇷', false),
('Libia', 'LY', '+218', '🇱🇾', false),
('Liechtenstein', 'LI', '+423', '🇱🇮', false),
('Lituania', 'LT', '+370', '🇱🇹', false),
('Luxemburgo', 'LU', '+352', '🇱🇺', false),
('Macedonia del Norte', 'MK', '+389', '🇲🇰', false),
('Madagascar', 'MG', '+261', '🇲🇬', false),
('Malasia', 'MY', '+60', '🇲🇾', false),
('Malaui', 'MW', '+265', '🇲🇼', false),
('Maldivas', 'MV', '+960', '🇲🇻', false),
('Malí', 'ML', '+223', '🇲🇱', false),
('Malta', 'MT', '+356', '🇲🇹', false),
('Marruecos', 'MA', '+212', '🇲🇦', false),
('Mauricio', 'MU', '+230', '🇲🇺', false),
('Mauritania', 'MR', '+222', '🇲🇷', false),
('Micronesia', 'FM', '+691', '🇫🇲', false),
('Moldavia', 'MD', '+373', '🇲🇩', false),
('Mónaco', 'MC', '+377', '🇲🇨', false),
('Mongolia', 'MN', '+976', '🇲🇳', false),
('Montenegro', 'ME', '+382', '🇲🇪', false),
('Mozambique', 'MZ', '+258', '🇲🇿', false),
('Namibia', 'NA', '+264', '🇳🇦', false),
('Nauru', 'NR', '+674', '🇳🇷', false),
('Nepal', 'NP', '+977', '🇳🇵', false),
('Nicaragua', 'NI', '+505', '🇳🇮', false),
('Níger', 'NE', '+227', '🇳🇪', false),
('Nigeria', 'NG', '+234', '🇳🇬', false),
('Noruega', 'NO', '+47', '🇳🇴', false),
('Nueva Zelanda', 'NZ', '+64', '🇳🇿', false),
('Omán', 'OM', '+968', '🇴🇲', false),
('Países Bajos', 'NL', '+31', '🇳🇱', false),
('Pakistán', 'PK', '+92', '🇵🇰', false),
('Palaos', 'PW', '+680', '🇵🇼', false),
('Palestina', 'PS', '+970', '🇵🇸', false),
('Papúa Nueva Guinea', 'PG', '+675', '🇵🇬', false),
('Paraguay', 'PY', '+595', '🇵🇾', false),
('Perú', 'PE', '+51', '🇵🇪', false),
('Polonia', 'PL', '+48', '🇵🇱', false),
('Portugal', 'PT', '+351', '🇵🇹', false),
('Reino Unido', 'GB', '+44', '🇬🇧', false),
('Ruanda', 'RW', '+250', '🇷🇼', false),
('Rumania', 'RO', '+40', '🇷🇴', false),
('Rusia', 'RU', '+7', '🇷🇺', false),
('Islas Salomón', 'SB', '+677', '🇸🇧', false),
('Samoa', 'WS', '+685', '🇼🇸', false),
('San Cristóbal y Nieves', 'KN', '+1-869', '🇰🇳', false),
('San Marino', 'SM', '+378', '🇸🇲', false),
('San Vicente y las Granadinas', 'VC', '+1-784', '🇻🇨', false),
('Santa Lucía', 'LC', '+1-758', '🇱🇨', false),
('Santo Tomé y Príncipe', 'ST', '+239', '🇸🇹', false),
('Senegal', 'SN', '+221', '🇸🇳', false),
('Serbia', 'RS', '+381', '🇷🇸', false),
('Seychelles', 'SC', '+248', '🇸🇨', false),
('Sierra Leona', 'SL', '+232', '🇸🇱', false),
('Singapur', 'SG', '+65', '🇸🇬', false),
('Siria', 'SY', '+963', '🇸🇾', false),
('Somalia', 'SO', '+252', '🇸🇴', false),
('Sri Lanka', 'LK', '+94', '🇱🇰', false),
('Suazilandia', 'SZ', '+268', '🇸🇿', false),
('Sudáfrica', 'ZA', '+27', '🇿🇦', false),
('Sudán', 'SD', '+249', '🇸🇩', false),
('Sudán del Sur', 'SS', '+211', '🇸🇸', false),
('Suecia', 'SE', '+46', '🇸🇪', false),
('Suiza', 'CH', '+41', '🇨🇭', false),
('Surinam', 'SR', '+597', '🇸🇷', false),
('Tailandia', 'TH', '+66', '🇹🇭', false),
('Taiwán', 'TW', '+886', '🇹🇼', false),
('Tanzania', 'TZ', '+255', '🇹🇿', false),
('Tayikistán', 'TJ', '+992', '🇹🇯', false),
('Timor Oriental', 'TL', '+670', '🇹🇱', false),
('Togo', 'TG', '+228', '🇹🇬', false),
('Tonga', 'TO', '+676', '🇹🇴', false),
('Trinidad y Tobago', 'TT', '+1-868', '🇹🇹', false),
('Túnez', 'TN', '+216', '🇹🇳', false),
('Turkmenistán', 'TM', '+993', '🇹🇲', false),
('Turquía', 'TR', '+90', '🇹🇷', false),
('Tuvalu', 'TV', '+688', '🇹🇻', false),
('Ucrania', 'UA', '+380', '🇺🇦', false),
('Uganda', 'UG', '+256', '🇺🇬', false),
('Uruguay', 'UY', '+598', '🇺🇾', false),
('Uzbekistán', 'UZ', '+998', '🇺🇿', false),
('Vanuatu', 'VU', '+678', '🇻🇺', false),
('Ciudad del Vaticano', 'VA', '+39-06', '🇻🇦', false),
('Vietnam', 'VN', '+84', '🇻🇳', false),
('Yemen', 'YE', '+967', '🇾🇪', false),
('Yibuti', 'DJ', '+253', '🇩🇯', false),
('Zambia', 'ZM', '+260', '🇿🇲', false),
('Zimbabue', 'ZW', '+263', '🇿🇼', false)
ON CONFLICT (name) DO NOTHING;
